[dev]
  framework = "#static"
  publish = "public"
  autoLaunch = false

[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs", "multer", "nodemailer", "cloudinary", "qrcode"]
  included_files = ["lib/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/p/*"
  to = "/p/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
